### ISSUE TITLE
How to Update MISP Docker Images/Container

### ISSUE THREAD

**Issue by iAmG-r00t** [MISP/x_old_misp_docker#13]
How can one update the images and containers without loosing past data, I tried updating it from the web Interface but it is not working.

**Comment by adulau** [comment]
If you have ssh access (and the docker has Internet access), you can basically do the following in the MISP directory:

~~~~
git pull origin 2.4
git submodule sync
git submodule update --remote
~~~~

I hope this helps.

**Comment by iAmG-r00t** [comment]
The first command origin 2.4 with origin 2.4 it's not working

**Comment by iAmG-r00t** [comment]
getting this error: fatal: Couldn't find remote ref 2.4

**Comment by adulau** [comment]
check the status of your git `git status` and on which branch you are `git branch`.

**Comment by iAmG-r00t** [comment]
Hey sorry about the late reply, the misp set up is a docker container....

**Comment by yaleman** [comment]
If you're running it using `docker-compose` and you haven't made any major changes since you originally built it, you should just be able to do the `docker-compose build`, `docker-comspose up -d` commands and it'll rebuild and reload the changed parts.

Given that the data's already stored outside the containers you shouldn't lose anything, but it'd be a good idea to ensure you've got a backup done.

**Comment by iAmG-r00t** [comment]
thank you

**Comment by shirley815** [comment]
Hello. I'm running docker misp, too. I'd like to update misp submodules. 
I tried to use docker-compose pull, docker-compose build and docker-comspose up -d. But I'm not sure if I update submodules successfully.

![image](https://user-images.githubusercontent.com/92505931/142548482-f9b5dec3-f88b-49e6-910d-8100c5964ad3.png)

By the way, I installed docker misp from https://github.com/coolacid/docker-misp.
