### ISSUE TITLE
I can login with browser, but only think that works is password.

### ISSUE THREAD

**Issue by CecilJackson** [MISP/x_old_misp_docker#131]
Not Found
Error: The requested address '/localhost/dashboards' was not found on this server.

**Comment by JustCodeIt4Head** [comment]
Hi,
is the Browser on the same Machine as the Docker Container? If not, you have to change the Value of MISP_BASEURL in your .env file from "localhost" to "" (So just two ") or to the IP of the Machine.
Im in the Process of Deploying MISP via Docker myselfe and let u know

**Comment by CecilJackson** [comment]
No it not.  I will try that.

Thanks

**Comment by CecilJackson** [comment]
If I use "" or IP I get this error:

Not Found
Error: The requested address '/users/localhost/users/routeafterlogin' was not found on this server.
MYSQL_HOST=misp_db
MYSQL_DATABASE=misp
MYSQL_USER=misp
MYSQL_PASSWORD=misp
MYSQL_ROOT_PASSWORD=misp

***@***.***
MISP_ADMIN_PASSPHRASE=admin
MISP_BASEURL=""

POSTFIX_RELAY_HOST=relay.fqdn
TIMEZONE=Europe/Brussels

DATA_DIR=./data

**Comment by CecilJackson** [comment]
How do you uninstall and reinstall.  I removed the directory, but did not remove database.

**Comment by JustCodeIt4Head** [comment]
Hi,
to do a complete reinstall delete both Containers created (misp_web + misp_db) and delete the Data Directory you have specified in the .env File (Default is a data Folder in the Folder you run the docker compose).

After that reinstall it and use a Domain to access it

**Comment by CecilJackson** [comment]
I did a rm and then rebuilt.   I add the "" and that worked.

How do I get docker to start at reboot.

**Comment by JustCodeIt4Head** [comment]
In the Docker Compose File for each Service there is a restart Option defined, for example restart: unless-stopped
If you want to start your Containers with the Machine booting, all services need the restart Option set to always instead of unless-stopped.

Depending on how much RAM / Cores and what Hard disk your Machine has, I would also suggest using the process manager of your Distribution (e.g. systemd) to start ur Containers with a delay if you use more then a few.
