### ISSUE TITLE
Env variables not all used

### ISSUE THREAD

**Issue by pkhabazi** [MISP/x_old_misp_docker#150]
The user login and password is always the same default even if you configure other values for the following variables:
- MISP_ADMIN_EMAIL 
- MISP_ADMIN_PASSPHRASE

Is this correct or am I missing something?

**Comment by fukusuket** [comment]
me too :0

**Comment by vaishnochaitanya** [comment]
Just added a fix where the docker will use the default values in these kind of cases. Feel free to report a bug.

**Comment by righel** [comment]
Addressed by @gvaishno  #153 PR.

**Comment by scmanjarrez** [comment]
Hello, I've encountered the same problem, the values set in `MISP_ADMIN_EMAIL` and `MISP_ADMIN_PASSPHRASE` are not configured in the web UI. It always uses the default values `admin@admin.test`/`admin`. I think the problem is that these values are hardcoded in `/var/www/MISP/app/model/User.php`, and are never updated to use the ones configured in the environment variables.
